"""update audit_logs table

Revision ID: 5d50d181da08
Revises: d8723f98ab4c
Create Date: 2025-02-24 09:10:38.307524

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d50d181da08'
down_revision = 'd8723f98ab4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('action_details',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('source_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('source_ip',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('action_details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('account_email')

    # ### end Alembic commands ###
