"""add audit_logs table

Revision ID: d8723f98ab4c
Revises: a91b476a53de
Create Date: 2025-02-24 02:27:03.171260

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8723f98ab4c'
down_revision = 'a91b476a53de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('audit_log_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('audit_log_action_type_idx', ['action_type'], unique=False)
        batch_op.create_index('audit_log_category_idx', ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('audit_log_category_idx')
        batch_op.drop_index('audit_log_action_type_idx')
        batch_op.drop_index('audit_log_account_id_idx')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
